name: build

on:
  push:
    branches: [master, main, Phase06]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore
        run: dotnet restore ./Phase06.sln

      - name: Build
        run: dotnet build ./Phase06.sln --configuration Release --no-restore

      - name: Test (with coverage)
        run: dotnet test ./Phase06.sln --configuration Release --no-restore --collect:"XPlat Code Coverage" --verbosity normal

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: **/TestResults/*/coverage.cobertura.xml
          fail_ci_if_error: true
